#Speech To Text Hugging Face

In [ ]:
!pip install transformers

In [ ]:
from transformers import pipeline

In [ ]:
import transformers
print(transformers.__version__)

4.52.4


###librosa is python package for audio and music analysis
###torch is a ml library used for nlp and computer vision

In [5]:
import librosa
import torch
import IPython.display as display
#Ipython is a interactive command line for python adn it can execute a single line of python code in quickly

from transformers import Wav2Vec2ForCTC, Wav2Vec2Tokenizer
import numpy as np

In [6]:
tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/163 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/291 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/85.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.60k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'Wav2Vec2CTCTokenizer'. 
The class this function is called from is 'Wav2Vec2Tokenizer'.
/usr/local/lib/python3.11/dist-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:720: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
  warnings.warn(


model.safetensors:   0%|          | 0.00/378M [00:00<?, ?B/s]

Some weights of Wav2Vec2ForCTC were not initialized from the model checkpoint at facebook/wav2vec2-base-960h and are newly initialized: ['wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [23]:
audio, sampling_rate = librosa.load('/v.m4a', sr = 16000)

<ipython-input-23-4289228105>:1: UserWarning: PySoundFile failed. Trying audioread instead.
  audio, sampling_rate = librosa.load('/v.m4a', sr = 16000)


In [24]:
audio, sampling_rate

(array([-5.4097222e-03, -1.1375937e-02, -9.7763110e-03, ...,
        -2.2627402e-09, -4.8468554e-09,  0.0000000e+00], dtype=float32),
 16000)

In [25]:
display.Audio('/v.m4a', autoplay=True)

In [26]:
input_values=tokenizer(audio, return_tensors='pt').input_values
input_values

tensor([[-1.4128e-01, -2.9699e-01, -2.5524e-01,  ..., -8.8417e-05,
         -8.8484e-05, -8.8358e-05]])

In [28]:
logits = model(input_values).logits
logits

tensor([[[ 10.1381, -25.2311, -25.0728,  ...,  -6.8527,  -7.8045,  -6.4760],
         [ 10.2945, -23.6119, -23.3945,  ...,  -5.8524,  -7.4760,  -5.1193],
         [ 11.0091, -23.6582, -23.4401,  ...,  -5.6770,  -7.7505,  -4.7627],
         ...,
         [  3.3711, -16.5827, -16.4545,  ...,  -4.0560,  -2.4498,  -2.3584],
         [  5.5413, -19.6297, -19.3926,  ...,  -6.4242,  -7.1864,  -5.2773],
         [  4.6029, -20.5787, -20.4284,  ...,  -6.7224,  -7.0345,  -4.8356]]],
       grad_fn=<ViewBackward0>)

In [30]:
predicted_ids = torch.argmax(logits, dim=-1)

In [31]:
transcriptions = tokenizer.batch_decode(predicted_ids)
transcriptions

['SPEECH TO TEXT ANALYSIS  IS REVOLUTIONIZING HOW WE INTERACT WITH TECHNAL']

Finally we got the output from a speech to text
